import 'Application/create_application.dart';
import 'Application/list_or_search_managing_apps.dart';
import 'Application/read_application_info.dart';
import 'Application/read_application_simple_info.dart';
import 'Application/OwnerOnlyOperations/edit_app_info.dart';
import 'Application/OwnerOnlyOperations/edit_app_manager_list.dart';
import 'Application/OwnerOnlyOperations/request_edit_app_vericode.dart';
import 'Application/OwnerOnlyOperations/reroll_app_secret.dart';
import 'Application/OwnerOnlyOperations/transfer_app_ownership.dart';
import 'Avatar/fetch_avatars.dart';
import 'Avatar/upload_avatar.dart';
import 'OAuth/APP/renew_oauth_token.dart';
import 'OAuth/APP/request_oauth_token.dart';
import 'OAuth/APP/set_custom_role.dart';
import 'OAuth/APP/verify_oauth_token.dart';
import 'OAuth/User/edit_or_create_oauth_authorization.dart';
import 'OAuth/User/fetch_oauth_authorization.dart';
import 'OAuth/User/grant_auth_code.dart';
import 'OAuth/User/list_or_search_oauth_authorization.dart';
import 'OAuth/User/revoke_oauth_authorization.dart';
import 'User/createuser.dart';
import 'User/login.dart';
import 'User/logout.dart';
import 'User/refreshtoken.dart';
import 'User/searchuser.dart';
import 'User/verifyToken.dart';
import 'User/Modify/change_or_add_contact_apply_loggedin.dart';
import 'User/Modify/change_or_add_contact_apply_notlogged.dart';
import 'User/Modify/request_change_or_add_contact_loggedin_vericode.dart';
import 'User/Modify/modify_user_info.dart';
import 'User/PasswordReset/get_reset_password_vericode.dart';
import 'User/PasswordReset/resetuserpassword.dart';
import 'User/UserVerification/resendverificationemail_loggedin.dart';
import 'User/UserVerification/resendverificationemail_notloggedin.dart';
import 'User/UserVerification/resendverifyphone_loggedin.dart';
import 'User/UserVerification/resendverifyphone_notloggedin.dart';
import 'User/UserVerification/verifyemail.dart';
import 'User/UserVerification/verifyphone.dart';

class AllExchangeMethods{
  static final createApp = createApplicationAPI;
  static final listOrSearchManagingApps = listOrSearchManagingAppsAPI;
  static final readAppInfo = readApplicationInfoAPI;
  static final readAppSimpleInfo = readApplicationSimpleInfoAPI;
  static final editAppInfo = editAPPInfoAPI;
  static final editAppManagerList = editAppManagerListAPI;
  static final requestVericodeToEditAPP = requestEditAppVericodeAPI;
  static final rerollAppSecret = rerollAppSecretAPI;
  static final transferAppOwnership = transferAppOwnershipAPI;
  static final fetchAvatars = fetchAvatarsAPI;
  static final uploadAvatar = uploadAvatarAPI;
  static final renewOAuthToken = renewOAuthTokenAPI;
  static final requestOAuthToken = requestOAuthTokenAPI;
  static final setOAuthCustomRole = setCustomRoleAPI;
  static final verifyOAuthToken = verifyOAuthTokenAPI;
  static final editOrCreateOAuthAuthorization = editOrCreateOAuthAuthorizationAPI;
  static final fetchOAuthAuthorization = fetchOAuthAuthorizationAPI;
  static final grantAuthCode = grantAuthCodeAPI;
  static final listOrSearchOAuthAuthorization = listOrSearchOAuthAuthorizationAPI;
  static final revokeOAuthAuthorization = revokeOAuthAuthorizationAPI;
  static final createUser = createUserAPI;
  static final userLogin = userLoginAPI;
  static final userLogout = userLogoutAPI;
  static final refreshUserToken = refreshUserTokenAPI;
  static final searchUser = searchUserAPI;
  static final verifyUserToken = verifyUserTokenAPI;
  static final requestChangeOrAddContactMethodVericodeWhileLoggedIn = requestChangeOrAddContactLoggedInVericode_API;
  static final changeOrAddContactMethodWhileLoggedIn = changeOrAddContactApply_LoggedIn_API;
  static final changeOrAddContactMethodWhileNotLoggedIn = changeOrAddContactApply_NotLogged_API;
  static final modifyUserInfo = modifyUserInfoAPI;
  static final requestResetUserPasswordVericode = getResetPasswordVericodeAPI;
  static final resetUserPassword = resetUserPasswordAPI;
  static final resendVerificationEmailWhileNotLoggedIn = resendVerificationEmail_NotLoggedIn_API;
  static final resendVerificationEmailWhileLoggedIn = resendVerificationEmail_LoggedIn_API;
  static final resendVerifyPhoneWhileNotLoggedIn = resendVerifyPhone_NotLoggedIn_API;
  static final resendVerifyPhoneWhileLoggedIn = resendVerifyPhone_LoggedIn_API;
  static final verifyUserEmail = verifyUserEmailAPI;
  static final verifyUserPhone = verifyUserPhoneAPI;
}